version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - app_service_DB__uri=postgresql://postgres:postgres@db:5432/app_service
      - app_service_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: app_service_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/app_service_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=app_service, app_service_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
